name: dartblade
description: Dartblade project for Webtechnologie Course
# version: 1.0.0
#homepage: https://www.example.com
#author: Tore Mielck
#author: Mario Odzga

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
